# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\ci\containers\000014qcqjp\tmp\build\80754af9\rsync-recipes\certifi-2018.1.18-python3.6target-win-32-on-winbuilder, last modified Fri Jan 26 09:22:32 2018
# ------------------------------------------------

package:
    name: certifi
    version: 2018.1.18
source:
    fn: certifi-2018.1.18.tar.gz
    sha256: edbc3f203427eef571f79a7692bb160a2b0f7ccaa31953e99bd17e307cf63f7d
    url: https://pypi.io/packages/source/c/certifi/certifi-2018.1.18.tar.gz
build:
    number: '0'
    preserve_egg_dir: 'True'
    script: python setup.py install
    string: py36_0
requirements:
    host:
        - python 3.6.4 h6538335_1
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
