# This file created by conda-build 3.0.15+56.gd43c51d4
# meta.yaml template originally from:
# C:\Users\builder\conda-win32\aggregate\requests-feedstock\recipe, last modified Tue Sep 19 18:20:16 2017
# ------------------------------------------------

package:
    name: requests
    version: 2.18.4
source:
    sha256: 9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e
    url: https://pypi.io/packages/source/r/requests/requests-2.18.4.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h964142b_1
requirements:
    build:
        - certifi 2017.7.27.1 py36h8287e07_0
        - python 3.6.2 h21b614c_11
        - setuptools 36.2.2 py36h3c0eabd_0
        - vc 14 h2379b0c_1
        - vs2015_runtime 14.0.25123 h98fd7d1_1
        - wincertstore 0.2 py36hcdd9a18_0
    host:
        - certifi 2017.7.27.1 py36h8287e07_0
        - python 3.6.2 h21b614c_11
        - setuptools 36.2.2 py36h3c0eabd_0
        - vc 14 h2379b0c_1
        - vs2015_runtime 14.0.25123 h98fd7d1_1
        - wincertstore 0.2 py36hcdd9a18_0
    run:
        - certifi >=2017.4.17
        - chardet >=3.0.2,<3.1.0
        - idna >=2.5,<2.7
        - python >=3.6,<3.7.0a0
        - urllib3 >=1.21.1,<1.23
test:
    imports:
        - requests
about:
    description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

        consumption.

        '
    dev_url: https://github.com/kennethreitz/requests
    doc_source_url: https://github.com/requests/requests/tree/master/docs
    doc_url: http://docs.python-requests.org/
    home: http://python-requests.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Python HTTP for Humans.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - sigmavirus24
