# This file created by conda-build 3.2.2
# ------------------------------------------------

package:
    name: vc
    version: 14
build:
    noarch: false
    number: '3'
    string: h0510ff6_3
    track_features:
        - vc14
requirements:
    run:
        - vs2015_runtime >=14.0.25123,<15.0a0
about:
    description: 'This metapackage is used to activate vc features without

        depending on Python.

        '
    dev_url: https://github.com/conda/conda/wiki/VC-features
    doc_url: https://github.com/conda/conda/wiki/VC-features
    home: https://github.com/conda/conda/wiki/VC-features
    license: Modified BSD License (3-clause)
    license_family: BSD
    summary: A meta-package to track VC features.
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: vs2015
        path: C:\ci\containers\000035alipn\tmp\build\80754af9\rsync-recipes\vs2015-14.0.25123-target-win-32-on-winbuilder
        version: 14.0.25123
