# This file created by conda-build 3.4.1
# meta.yaml template originally from:
# C:\ci\containers\0000384lp1a\tmp\build\80754af9\rsync-recipes\conda-4.4.10-python3.6target-win-32-on-win-64, last modified Fri Feb  9 16:07:47 2018
# ------------------------------------------------

package:
    name: conda
    version: 4.4.10
source:
    git_rev: 9d9cc69ad10b6df25b63062cbd30f4be92cadf35
    git_url: https://github.com/conda/conda.git
build:
    always_include_files:
        - Scripts/activate
        - Scripts/activate.bat
        - Scripts/deactivate
        - Scripts/deactivate.bat
    entry_points:
        - conda = conda.cli:main
        - conda-env = conda_env.cli.main:main
    number: '0'
    string: py36_0
requirements:
    build:
        - m2-base 1.0.0 2
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-ca-certificates 20150426 103
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-curl 7.47.1 3
        - m2-dash 0.5.8 2
        - m2-db 5.3.28 3
        - m2-expat 2.1.1 2
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gdbm 1.11 4
        - m2-gettext 0.19.7 4
        - m2-git 2.8.1 2
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-heimdal 1.5.3 10
        - m2-heimdal-libs 1.5.3 10
        - m2-icu 56.1 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libcurl 7.47.1 3
        - m2-libdb 5.3.28 3
        - m2-libedit 3.1 20150326
        - m2-libexpat 2.1.1 2
        - m2-libffi 3.2.1 2
        - m2-libgdbm 1.11 4
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libidn 1.32 2
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libmetalink 0.1.2 3
        - m2-libopenssl 1.0.2.g 2
        - m2-libp11-kit 0.23.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libsqlite 3.10.0.0 2
        - m2-libssh2 1.6.0 2
        - m2-libtasn1 4.7 2
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-openssh 7.1p2 2
        - m2-openssl 1.0.2.g 2
        - m2-p11-kit 0.23.2 2
        - m2-perl 5.22.1 2
        - m2-perl-authen-sasl 2.16 3
        - m2-perl-convert-binhex 1.123 3
        - m2-perl-encode-locale 1.04 2
        - m2-perl-error 0.17024 2
        - m2-perl-file-listing 6.04 3
        - m2-perl-html-parser 3.71 4
        - m2-perl-html-tagset 3.20 3
        - m2-perl-http-cookies 6.01 3
        - m2-perl-http-daemon 6.01 3
        - m2-perl-http-date 6.02 3
        - m2-perl-http-message 6.06 3
        - m2-perl-http-negotiate 6.01 3
        - m2-perl-io-socket-ssl 2.016 2
        - m2-perl-io-stringy 2.111 2
        - m2-perl-libwww 6.13 2
        - m2-perl-lwp-mediatypes 6.02 3
        - m2-perl-mailtools 2.14 2
        - m2-perl-mime-tools 5.506 2
        - m2-perl-net-http 6.09 2
        - m2-perl-net-smtp-ssl 1.02 2
        - m2-perl-net-ssleay 1.72 2
        - m2-perl-termreadkey 2.33 2
        - m2-perl-timedate 2.30 3
        - m2-perl-uri 1.68 2
        - m2-perl-www-robotrules 6.02 3
        - m2-sed 4.2.2 3
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-util-linux 2.26.2 2
        - m2-vim 7.4.1721 2
        - m2-which 2.21 3
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
        - python 3.6.4 h6538335_1
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - conda-env >=2.6
        - menuinst
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.6,<3.7.0a0
        - requests >=2.12.4,<3
        - ruamel_yaml >=0.11.14
    run_constrained:
        - conda-build >=2.1
        - cytoolz >=0.8.1
        - setuptools >=31.0.1
test:
    commands:
        - conda activate base
        - FOR /F "delims=" %%i IN ('python -c "import sys; print(sys.version_info[0])"')
            DO set "PYTHON_MAJOR_VERSION=%%i"
        - set TEST_PLATFORM=win
        - FOR /F "delims=" %%i IN ('python -c "import random as r; print(r.randint(0,4294967296))"')
            DO set "PYTHONHASHSEED=%%i"
        - set
        - conda info
        - py.test tests -m "not integration and not installed" -vv
        - conda create -y -p .\built-conda-test-env
        - conda activate .\built-conda-test-env
        - echo %CONDA_PREFIX%
        - IF NOT "%CONDA_PREFIX%"=="%CD%\built-conda-test-env" EXIT /B 1
    imports:
        - conda
        - conda_env
    requires:
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment

        management system for installing multiple versions of software packages

        and their dependencies and switching easily between them. It works on

        Linux, OS X and Windows, and was created for Python programs but can

        package and distribute any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/docs/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
