# This file created by conda-build 3.0.27
# meta.yaml template originally from:
# C:\ci\containers\00001q49lhm\tmp\build\80754af9\rsync-recipes\pip-9.0.1-python3.6target-win-32-on-winbuilder, last modified Fri Oct 27 10:17:38 2017
# ------------------------------------------------

package:
    name: pip
    version: 9.0.1
source:
    fn: pip-9.0.1.tar.gz
    patches:
        - 0001-update-vendorings-to-match-master.patch
        - 0002-fix-up-references-to-vendored-requests-deps.patch
    sha256: 09f243e1a7b461f654c26a725fa373211bb7ff17a9300058b205c61658ca940d
    url: https://pypi.io/packages/source/p/pip/pip-9.0.1.tar.gz
build:
    disable_pip: 'True'
    entry_points:
        - pip = pip:main
    number: '4'
    string: py36had87c14_4
requirements:
    host:
        - certifi 2017.7.27.1 py36h8287e07_0
        - python 3.6.3 h28e8c7f_1
        - setuptools 36.5.0 py36h7f22f53_0
        - vc 14 h2379b0c_2
        - vs2015_runtime 14.0.25123 hd4c4e62_2
        - wincertstore 0.2 py36hcdd9a18_0
    run:
        - python >=3.6,<3.7.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
